#!/usr/local/bin/perl -w

# CGI for Displaying documents for the MMS
#
# $Source$
#
# $Revision$
#
# $Date$
#
# $Author$
#
# $Locker$
#
# $Log$
#
#
#
#
use strict;
#use integer;
#
$| = 1;
#
# get all required libraries and modules
use MMS_Header qw(:Constants);
use UI_Widgets qw(:Functions);
use DB_Utilities_Lib qw(:Functions);

use DBI;
use DBD::Oracle qw(:ora_types);
use CGI;

# create cgi object for processing
my $mmscgi = new CGI;

# change any environment variables here
# set schema name
my $schema = $mmscgi->param("schema");

# Get username from the previous form for use later
my $username = $mmscgi->param("username");
my $userid = $mmscgi->param("userid");
&checkLogin ($username, $userid, $schema);

# tell the browser that this is an html page using the header method
print $mmscgi->header('text/html');


###################################################################################################################################
###################################################################################################################################

# output page header
print "<html>\n";
print "<head>\n";
print "<title>MMS Display Document</title>\n";
print "<!-- include external javascript code -->\n";
print "   <script src=$MMSJavaScriptPath/utilities.js></script>\n";
#print "   <script src=$MMSJavaScriptPath/widgets.js></script>\n";
print " \n";
print "<!-- declare javascript functions unique to this form -->\n";
print " \n";
print "</head>\n";
print "<body background=$MMSImagePath/background.gif text=#000099 link=#0000ff vlink=#0000ff alink=#0000ff topmargin=0 leftmargin=0>\n";

# set default font atributes
print "<font face=\"$MMSFontFace\" color=$MMSFontColor>\n";

my $command='';
my $attachementid='';
my $sqlquery='';
my $csr;
my $status;
my @values;
my $filepath = $MMSFullDocPath;
my $remote_path='';
my $filename='';
my $filedata='';
my $message='';
my $urllocation='';
my @fileStats;

# Connect to the oracle database and generate an object 'handle' to the database
my $dbh = db_connect();

# set up form for whole page
print "<br><center>\n";
print "<table border=0 width=750><tr><td>\n";

# setup form for the page (use filename_form as name of form)
print "<form name=myform action=$ENV{SCRIPT_NAME} method=post>\n";
# use a hidden field to tell the next cgi what to do
print "<input type=hidden name=command value=mycommand>\n";
# use hidden fields to keep track of the user.  Populate them with the username and the userid
print "<input type=hidden name=username value=$username>\n";
print "<input type=hidden name=userid value=$userid>\n";
print "<input type=hidden name=schema value=$schema>\n";

$command = $mmscgi->param('command');
$attachementid = $mmscgi->param('attachementid');
if (!(defined($command))) { $command='none'; }
if ($command eq "pdf" || $command eq "redline") {
    $documentid = $mmscgi->param('documentid');
    $commentid = $mmscgi->param('commentid');
    if ($command eq 'pdf') {
        $filename = "$MMSType" . lpadzero($documentid,6) . ".pdf";
    } elsif ($command eq 'redline') {
        $version = $mmscgi->param('version');
        $filename = "$MMSType" . lpadzero($documentid,6) . "-" . lpadzero($commentid, 4) . "-" . lpadzero($version, 3) . ".doc";
    }
    print "<input type=hidden name=filename value=$filename>\n";
    # get file from db and save it on the server
    $dbh->{LongReadLen} = 100000000;
        $sqlquery = "SELECT attachmentid,decisionid,mimetype,filename,attachment FROM $schema.attachments WHERE attachmentid = $attachementid";
    eval {
        $csr = $dbh->prepare($sqlquery);
        $status = $csr->execute;
        @values = $csr->fetchrow_array;
        $csr->finish;
    };
    if ($status && $#values >=0 && defined($values[0]) && !($@)) {
        # save read file to webserver
        my ($id,$decisionid,$mimetype,$attachmentfilename,$attachment) = @values;
        $filename = $decisionid . "-" . $attachmentfilename;
        $filedata = $attachment;
        if (open (FH2, "| ./File_Utilities.pl --command=writeFile --fullFilePath=$MMSFullDocPath/$filename --protection=0777")) {
            print FH2 $filedata;
            close (FH2);
            @fileStats = stat "$MMSFullDocPath/$filename";
            #$status = chmod 0775, "$MMSFullDocPath/$filename";
            
            # display the file
            $urllocation = "$MMSDocPath/$filename";
        } else {
            $message = errorMessage($dbh,$username,$userid,$schema,"write attachment $filename to server.",$@);
        }
    } else {
        $message = errorMessage($dbh,$username,$userid,$schema,"attachment $filename, not found in database.",$@);
    }


}

 
#=============================================================================================================

# display any messages generated by the script
print "<script language=javascript><!--\n";
if (defined($message) && $message gt " ") {
    print doAlertBox( text => $message, includeScriptTags => 'F');
}

# send the frame to the requested url
if (defined ($urllocation) && $urllocation gt ' ') {
    # close connection to the oracle database
    db_disconnect($dbh);
    print "   var newurl ='$urllocation';\n";
    print "   var myDate = new Date();\n";
    print "   var winName = myDate.getTime();\n";
    print "   if ($fileStats[7] >= 1048576) {\n";
    print "       if (confirm('Image is " . int($fileStats[7]*100/1048576)/100.0 . "MB, do you wish to display it?')) {\n";
    print "           var newwin = window.open(\"\",winName);\n";
    print "           newwin.creator = self;\n";
    print "           newwin.location=newurl;\n";
    print "       }\n";
    print "   } else {\n";
    print "       var newwin = window.open(\"\",winName);\n";
    print "       newwin.creator = self;\n";
    print "       newwin.location=newurl;\n";
    print "   }\n";

} else {
    db_disconnect($dbh);

    print "   self.close();\n";
}
print "//--></script>\n";

#=============================================================================================================





print "</form>\n";


print "<br><br>\n";

# close table for whole page
print "</td></tr></table></center>\n";

# end font atributes for page
print "</font>\n";

# close connection to the oracle database
db_disconnect($dbh);

print $mmscgi->end_html;
